name: Deploy Vue.js to NoMash-Library

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install
      
      - name: Verify dependencies
        run: |
          echo "Verifying vite installation..."
          npm list vite
          npm list @vitejs/plugin-vue
          echo "Checking vite executable..."
          which vite || echo "vite not in PATH"
          ls -la node_modules/.bin/vite || echo "vite not in node_modules/.bin"
      
      - name: Build with Vite
        run: |
          echo "Current directory: $(pwd)"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Vite version: $(npx vite --version)"
          echo "Checking node_modules structure:"
          ls -la node_modules/.bin/ | grep vite
          echo "Checking package-lock.json:"
          ls -la package-lock.json
          echo "Starting build..."
          npx vite build
        shell: bash
        env:
          NODE_ENV: production
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 